### ISSUE TITLE
Summary: Exceeds Expectations!

### ISSUE THREAD

**Issue by melissamcewen** [ricwarw/TeaCozy#1]
Hi I'm with Codeacademy and I reviewed your project just now. Great job! The site looks amazing!

Nice extra touch using flex box! Flex box is an excellent way to lay things out and I'm glad you decided to explore it. 

I opened up a few minor issues with the style and HTML. They are easy fixes.

As a further challenge, consider adding alt tags to describe your images. People with disabilities use the alt tag to understand the content of an image

http://accessibility.psu.edu/images/imageshtml/

Also search engines like Google look for this information. So it is highly recommended for Search Engine Optimization.

**Comment by ricwarw** [comment]
Hi - thanks so much for the feedback! Feels like I'm slowly getting the hang of it.. 👍
