### ISSUE TITLE
Error: height in img tag

### ISSUE THREAD

**Issue by melissamcewen** [ricwarw/TeaCozy#4]
https://github.com/ricwarw/TeaCozy/blob/master/index.html#L11
(Subtlety) so here you have height="50px". With the height attribute for images, the units are already in pixels, so it only needs to be height="50"

BUT best practices is to use CSS to style it. If you only need to style this one image, assign it an ID  like 
```html
        <img src="./resources/images/img-tea-cozy-logo.png" alt="Tea Cozy Logo" id="logo">
```

then in your css you can style it in 
```
#logo {
   height: 50px; 
}
```

you can read more here
https://html.com/attributes/img-height/

**Comment by ricwarw** [comment]
Makes sense - thanks! Fixed.
